version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /Microsoft.Security.Application.Encoder.UnitTests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /Microsoft.Security.Application.Encoder
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /Microsoft.Security.Application.HtmlSanitization.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /Microsoft.Security.Application.HtmlSanitization
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
